### ISSUE TITLE
Better health check

### ISSUE THREAD

**Issue by Arcanemagus** [spritsail/tautulli#1]
With Tautulli v2.1.32 a new URL path of `/status` was added specifically for health checks, you may want to switch over to how our [official image does it](https://github.com/Tautulli/Tautulli-Docker/blob/a498f3e8a098b3b3234f17b57f533d618b8adb34/Dockerfile#L80) as it will work in a few cases where your current health check will fail:
* When the API is disabled by the user
* When the user has enabled HTTPS within the container itself

**Comment by frebib** [comment]
Ooh lovely, I'll try that, thanks!
(I like the arnold endpoint, I'll be sad to see it go :cry:)

**Comment by frebib** [comment]
Hm, in reviewing this I would argue that the "default" configuration is good for most users. Anyone running an advanced configuration will want to override the healthcheck anyway because we can't even assume simple things like the bind IP address, port or anything. I suppose in the best case the healthcheck script would parse the configuration for the protocol, address, port etc.
I'm going to consider this acceptable for now until someone wants to tell me it's not working for them, then I'll probably fix it :smile:
